# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d221bdc4297523b5bddf1af3f6d97328e3fc430e080a46d7550a58af38eaf7f87bb0164929fa046daa2e54c6694013b6ec55079c42367270f50f0cbfe91f2d7

test:
  secret_key_base: 0a692b4acb8ba40e496287ca5796726ebeb7f9bf3541ecae5a2f364b6de4587793c2438ee4a71943fd86125bdac729707de9d15f823eed223eb0dd66b46b070f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
